- name: Install Debian packages
  ansible.builtin.package:
    name:
      - i3
      - polybar
      - arandr
      - autorandr
      - snap
      - snapd
      - network-manager
    state: latest
- name: Install Snap packages
  community.general.snap:
    name:
      - core
      - spotify
- name: Install Snap classic packages
  community.general.snap:
    name: goland
    classic: true
- name: Enable Network Manager
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: yes
    state: started
- name: Install neovim
  apt:
    deb: https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.deb
- name: Add Google official GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: Add Kubernetes Repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes
    mode: 0600
- name: Installing kubectl
  apt:
    name: kubectl
    state: present
