- name: Install packages
  ansible.builtin.package:
    name:
      - htop
      - tmux
      - autojump
      - neofetch
      - vim
      - gucharmap
      - stow
      - zsh
      - direnv
      - nodejs
      - npm
      - ripgrep
      - gh
    state: latest
- name: Install tree-sitter NPM
  community.general.npm:
    name: tree-sitter-cli
    global: true
- name: Install typescript NPM
  community.general.npm:
    name: typescript
    global: true
- name: Install prettierd NPM
  community.general.npm:
    name: "@fsouza/prettierd"
    global: true
