- name: Install Homebrew packages
  homebrew:
    name:
      - ansible
      - htop
      - tmux
      - autojump
      - neofetch
      - vim
      - gucharmap
      - stow
      - zsh
      - direnv
      - nodejs
      - npm
      - ripgrep
      - gh
      - fd
      - yabai
      - skhd
      - jq
      - sketchybar
      - borders
      - go
      - gopls
      - ifstat
      - atuin
      - fzf
      - pngpaste
      - svim
      - lua
      - luarocks
      - switchaudio-osx
      - nowplaying-cli
    state: latest
  ignore_errors: yes

- name: Install Ghostty
  homebrew:
    name:
      - ghostty
    state: present
  ignore_errors: yes

# - name: Check if VSCode is installed
#   command: brew list --cask --versions visual-studio-code
#   register: vscode_installed
#   changed_when: false

# - name: Install VSCode using Homebrew
#   homebrew:
#     name: visual-studio-code
#   when: vscode_installed.rc != 0

- name: Install Homebrew head packages
  homebrew:
    name:
      - neovim
    state: head

- name: Clone SbarLua repository
  git:
    repo: https://github.com/FelixKratz/SbarLua.git
    dest: /tmp/SbarLua

- name: Install SbarLua
  command: make install
  args:
    chdir: /tmp/SbarLua

- name: Remove SbarLua temporary directory
  file:
    path: /tmp/SbarLua
    state: absent

- name: Install Lunajson using Luarocks
  command: luarocks install lunajson
  become: yes

- name: Install yfinance using pip
  pip:
    executable: pip3
    name: yfinance
    extra_args: --break-system-packages
