- name: Install Homebrew packages
  homebrew:
    name:
      - htop
      - tmux
      - autojump
      - neofetch
      - vim
      - gucharmap
      - stow
      - zsh
      - direnv
      - nodejs
      - npm
      - ripgrep
      - gh
      - fd
      - yabai
      - skhd
      - jq
      - sketchybar
      - borders
      - go
      - gopls
      - ifstat

- name: Check if VSCode is installed
  command: brew list --cask --versions visual-studio-code
  register: vscode_installed
  changed_when: false

- name: Install VSCode using Homebrew
  homebrew:
    name: visual-studio-code
  when: vscode_installed.rc != 0

- name: Install Homebrew head packages
  homebrew:
    name:
      - neovim
    state: head
