- name: Check SIP Status
  shell: 'csrutil status | grep "System Integrity Protection status: "'
  register: sip_status
  changed_when: false
  check_mode: no

- name: Copy SKHD Config
  copy:
    src: "{{ '~/.config/skhd/skhd_sip_enabled.conf' if 'enabled' in sip_status.stdout else '~/.config/skhd/skhd_sip_disabled.conf' }}"
    dest: "~/.config/skhd/skhdrc"
  changed_when: true

- name: Check SKHD status
  command: launchctl list com.koekeishiya.skhd
  register: skhd_status
  changed_when: false
  failed_when: false
  ignore_errors: yes # Ignore errors if the service is not found

- name: Start SKHD
  command: skhd --start-service
  when: skhd_status.rc != 0

- name: Restart SKHD
  command: skhd --restart-service
  when: skhd_status.rc == 0

- name: Start Sketchybar
  command: brew services restart sketchybar
