- name: Check SIP Status
  shell: 'csrutil status | grep "System Integrity Protection status: "'
  register: sip_status
  changed_when: false
  check_mode: no

- name: Copy SKHD Config
  copy:
    src: "{{ '~/.config/skhd/skhd_sip_enabled.conf' if 'enabled' in sip_status.stdout else '~/.config/skhd/skhd_sip_disabled.conf' }}"
    dest: "~/.config/skhd/skhdrc"
  changed_when: true

- name: Start Yabai
  command: yabai --start-service

- name: Start SKHD
  command: skhd --start-service

- name: Start Sketchybar
  command: brew services start sketchybar