#!/usr/bin/env sh
#YABAI STUFF

# Unload the macOS WindowManager process
# launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist >/dev/null 2>&1 &

SIP_STATUS="$(csrutil status | grep 'System Integrity Protection status: ')"
if [[ "$SIP_STATUS" =~ "enabled" ]]; then
  echo "SIP is enabled..."
  # Run your shell commands here if SIP is enabled
else
  echo "SIP is disabled..."
  sudo yabai --load-sa
  yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
fi

yabai -m signal --add event=display_added action="echo \"display added\" && sleep 0.1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="echo \"display removed\" && sleep 0.1 && $HOME/.config/yabai/create_spaces.sh"
# yabai -m signal --add event=display_resized action="brew services restart sketchybar"

# Change how yabai looks
yabai -m config mouse_follows_focus on \
  window_placement second_child \
  window_shadow float \
  window_opacity on \
  active_window_opacity 0.95 \
  normal_window_opacity 0.8 \
  split_ratio 0.50 \
  auto_balance off \
  mouse_modifier ctrl \
  mouse_drop_action swap \
  \
  bottom_padding 20 \
  left_padding 20 \
  right_padding 20 \
  window_gap 10 \
  external_bar all:45:0

# top_padding 20 \
# mouse_follows_focus off \
# focus_follows_mouse on \
# mouse_action1 move \
# mouse_action2 resize \
#
# active_window_border_color 0xffe1e3e4 \
# normal_window_border_color 0xff2a2f38 \
# insert_feedback_color 0xff9dd274 \
# window_opacity_duration 0.25 \

echo "before spaces"

# Create spaces
$HOME/.config/yabai/create_spaces.sh

echo "spaces created"

# My custom space names for my 3 monitor setup. These names are used in some of my scripts.
yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four
yabai -m space 5 --label five
yabai -m space 6 --label six
# yabai -m space 7 --label six
# yabai -m space 8 --label six
# yabai -m space 9 --label nine

echo "after spaces"

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Flux$" manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Private Internet Access$" manage=off
yabai -m rule --add app='^Arc$' title='^Space.*$' manage=off sub-layer=above
# yabai -m rule --add app="^Arc$" subrole='AXSystemDialog' manage=off mouse_follows_focus=off

yabai -m config layout bsp

#find ~/Library/Parallels/Applications\ Menus/ -maxdepth 3 -type f | awk -F'/' '{ print $NF; }' | awk '{$1=$1};1' | sort | uniq | tr "\n" "\0" | xargs -0 -I{} yabai -m rule --add app="^{}\$" title=".*" manage=on
echo "yabai configuration loaded.."

#END
