- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
      when: ansible_facts['distribution'] == "Debian"

  tasks:
    - include: tasks/packages.yml
    - include: tasks/fonts.yml
    - include: tasks/debian_packages.yml
      when: ansible_facts['distribution'] == "Debian"
