- name: Setup MacOSX Environment
  hosts: localhost
  gather_facts: yes
  pre_tasks:
    - name: Check Homebrew is installed
      command: which brew
      register: brew_installed
    - name: Installing Homebrew
      shell: CI=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: not brew_installed
  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
    - name: Add homebrew tap
      homebrew_tap:
        name:
          - koekeishiya/formulae
          - FelixKratz/formulae
          - nikitabobko/tap
        state: present
    - name: Install MacOSX packages
      import_tasks: osx/packages.yml
    - name: Install fonts
      import_tasks: osx/fonts.yml
    - name: Install keyboard
      import_tasks: osx/keyboard.yml
    - name: Install MacOSX cask packages
      import_tasks: osx/cask.yml
    - name: Install MacOSX npm packages
      import_tasks: osx/npm.yml
    # - name: Run Utilities
    #   import_tasks: osx/utilities.yml
    - name: Stow common
      import_tasks: common/stow.yml
    - name: Stow MacOSX configs
      command: stow -vv -t ~ -d {{ playbook_dir }}/.. {{ item.path }}
      with_items:
        - { name: "Yabai", path: "yabai" }
        - { name: "SKHD", path: "skhd" }
        - { name: "Sketchybar", path: "sketchybar" }
        - { name: "Borders", path: "borders" }
        - { name: "Atuin", path: "atuin" }
        - { name: "SketchyVim", path: "svim" }
        - { name: "k9s", path: "k9s" }
        # - { name: "Aerospace", path: "aerospace" }
    # - name: Start Yabai
    #   import_tasks: osx/yabai.yml
    - name: Start Services
      import_tasks: osx/services.yml
