return {}
-- return {
--   {
--     "olimorris/codecompanion.nvim",
--     dependencies = {
--       "nvim-lua/plenary.nvim",
--       "nvim-treesitter/nvim-treesitter",
--     },
--     opts = {
--       strategies = {
--         -- Change the default chat adapter and model
--         chat = {
--           adapter = {
--             name = "copilot",
--             model = "gpt-5",
--           },
--           keymaps = {
--             send = {
--               modes = { n = "<CR>", i = { "<C-g>", "<C-v>" } },
--             },
--           },
--         },
--         inline = {
--           adapter = {
--             name = "copilot",
--             model = "gpt-5",
--           },
--         },
--         cmd = {
--           adapter = {
--             name = "gemini-cli",
--           },
--         },
--       },
--       adapters = {
--         acp = {
--           gemini_cli = function()
--             return require("codecompanion.adapters").extend("gemini_cli", {
--               defaults = {
--                 auth_method = "gemini-api-key",
--               },
--             })
--           end,
--         },
--       },
--       -- NOTE: The log_level is in `opts.opts`
--       opts = {
--         log_level = "DEBUG",
--       },
--     },
--   },
--
--   {
--     "MeanderingProgrammer/render-markdown.nvim",
--     ft = { "markdown", "codeckompanion" },
--   },
--
--   {
--     "saghen/blink.cmp",
--     opts = {
--       sources = {
--         per_filetype = {
--           codecompanion = { "codecompanion" },
--         },
--       },
--     },
--   },
-- }
