return {}
-- return {
--   "neovim/nvim-lspconfig",
--   opts = {
--     servers = {
--       gopls = {
--         settings = {
--           gopls = {
--             semanticTokens = true,
--             -- buildFlags = { "-tags=cluster,integration,operator" },
--             analyses = {
--               unusedparams = true,
--             },
--             staticcheck = true,
--             hints = {
--               assignVariableTypes = true,
--               compositeLiteralFields = true,
--               compositeLiteralTypes = true,
--               constantValues = true,
--               functionTypeParameters = true,
--               parameterNames = true,
--               rangeVariableTypes = true,
--             },
--           },
--         },
--       },
--     },
--   },
-- }
